### ISSUE TITLE
TypeError: SpriteGenerator is not a constructor

### ISSUE THREAD

**Issue by Akash187** [binoy638/sprite-vtt-generator#1]
Getting this error. `TypeError: SpriteGenerator is not a constructor`
Use node version `v16.8.0`
<img width="1079" alt="Screenshot 2023-04-21 at 10 57 38 PM" src="https://user-images.githubusercontent.com/21134455/233698841-e17492e4-a886-43fa-9457-4f46cb07eb09.png">

**Comment by Akash187** [comment]
I fixed it by changing the index.js file generated in the package. The export syntax seems to cause the issue. Still need to be fixed so that I did not need to tweak the node module file.
```
// exports.default = SpriteGenerator;
module.exports = SpriteGenerator;
```

**Comment by binoy638** [comment]
@Akash187 Thanks for raising the issue.
I have updated the package, please install the latest version.

**Comment by Akash187** [comment]
@binoy638 thanks, the issue is fixed.
